# Generated by Django 3.2.9 on 2021-12-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_delivery',
            field=models.DateTimeField(verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PAID', 'Оплачен'), ('DELIVERING', 'В доставке'), ('DELIVERED', 'Доставлен')], max_length=12, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
