# Generated by Django 3.2.9 on 2021-12-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211215_1202'),
        ('order', '0003_auto_20211215_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ManyToManyField(to='catalog.Product'),
        ),
    ]
