# Generated by Django 3.2.9 on 2021-12-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211215_1202'),
        ('order', '0006_auto_20211215_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ManyToManyField(related_name='products', to='catalog.Product'),
        ),
    ]
