# Generated by Django 3.2.9 on 2021-12-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211215_1202'),
        ('order', '0010_auto_20211215_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Продукт - Количество',
            },
        ),
        migrations.RunSQL('insert into order_productamount (id, product_id, amount) values (1, 1, 1);'),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.productamount'),
            preserve_default=False,
        ),
    ]
