# Generated by Django 3.2.9 on 2021-12-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20211215_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_amount',
        ),
    ]
