# Generated by Django 3.2.9 on 2021-12-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211215_1202'),
        ('order', '0012_rename_product_order_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productamount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
    ]
