# Generated by Django 3.2.9 on 2021-12-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_productamount_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='product_amount',
            field=models.ManyToManyField(to='order.ProductAmount'),
        ),
    ]
